### ISSUE TITLE
Add 2020 to %Dollar_convert

### ISSUE THREAD

**Issue by rpitingolo** [ptatian/uiautos#28]
@ptatian FYI we need to add 2020 to the dollar convert macro in order to finish the property update.

**Comment by ptatian** [comment]
Thanks, @rpitingolo. The procedure for this change is for someone to fork this repo, make the necessary changes to the macro, and then make a pull request that I will need to approve. Let me know if you have questions.

**Comment by ptatian** [comment]
Hi @rpitingolo I've merged the updated code. You need to update the macro code on L:. I think you can just pull it from the remote but you can also just copy the new macro.

**Comment by rpitingolo** [comment]
Thank you @ptatian I ran sync.bat on L and it pulled it down from the master branch.
