### ISSUE TITLE
Add partial 2024 to dollar_convert

### ISSUE THREAD

**Issue by rpitingolo** [ptatian/uiautos#57]
We need to update 2023 to ANNUAL and add 2024 for the months that are available in order to finish the Real Property update.

**Comment by ptatian** [comment]
Thanks, @rpitingolo . Would you be able to send me the updated code?

**Comment by rpitingolo** [comment]
@ptatian I am going to finish working on the update after my morning meetings.

**Comment by ptatian** [comment]
@rpitingolo Macro code has been updated in SAS1 and K drive repos.

**Comment by rpitingolo** [comment]
@ptatian thanks!!
